server:
  port: 7072
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7071/eureka/
      
spring:
  application:
    name: serviceHI
