server:
  port: 7076
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7071/eureka/

spring:
  application:
    name: SpringZuul
    
zuul:
  routes:
    rib:
      path: /rib/**
      serviceId: SpringRibbon
    fig:
      path: /fig/**
      serviceId: SpringFeign
